### ISSUE TITLE
Add action 'update using case replace' 

### ISSUE THREAD

**Issue by joaompinto** [UniPipe/openpipe#35]
```yaml
- map using case:
    technology:
      Apache: $ exe.endswith('/nginx') and 'master' in basecmd $
      Ruby: $ exe == 'ruby' or exe.endswith('/ruby')$
      Node: $ exe == 'node' or exe.endswith('/node')$
      Python: $basecmd.startswith('python')$
      Java: cmdline[0] == 'java'
      Nginx: $ exe.endswith('/nginx') and 'master' in cmdline[0] $
      Other: True
```
